version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  - dotnet --version
before_build:
  - nuget restore
  - choco install codecov
build_script:
  - dotnet build -c Release
test_script:
- ps: >-
    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test SpeldesignBotCore.xUnit.Tests/SpeldesignBotCore.xUnit.Tests.csproj" -filter:"+[SpeldesignBotCore*]* -[SpeldesignBotCore*]*Tests.*" -oldstyle -output:"opencoverCoverage.xml"
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
    codecov -f "opencoverCoverage.xml"
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
