version: 1.0.{build}
image: Visual Studio 2017
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  - dotnet --version
build_script:
  - dotnet build -c Release
test_script:
- ps: >-
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1

    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    dotnet tool install --global coveralls.net --version 1.0.0	
    
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" ""SpeldesignBotCore.xUnit.Tests\bin\Release\netcoreapp2.0\SpeldesignBotCore.xUnit.Tests.dll"" -noshadow -appveyor" -filter:"+[SpeldesignBotCore*]* -[SpeldesignBotCore*]*Tests.*" -oldStyle -output:"opencoverCoverage.xml"

    csmacnz.Coveralls --help
    dir

    csmacnz.Coveralls --opencover -i opencoverCoverage.xml --useRelativePaths --serviceName appveyor --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
