version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  - dotnet --version
before_build:
  - nuget restore
  - choco install codecov
build_script:
  - dotnet build -c Release
test_script:
- ps: >-
    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"SpeldesignBotCore.xUnit.Tests\bin\Release\netcoreapp2.1\SpeldesignBotCore.xUnit.Tests.dll -noshadow -appveyor" -filter:"+[SpeldesignBotCore*]* -[SpeldesignBotCore*]*Tests.*" -output:"opencoverCoverage.xml"

    codecov -f "opencoverCoverage.xml"
    
    # Needed to make the CI Build fail, because OpenCover doesn't seem to fail the build even if the unit tests fail
    dotnet test SpeldesignBotCore.xUnit.Tests/SpeldesignBotCore.xUnit.Tests.csproj
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL